#!/usr/bin/env ruby

local_ref = STDIN.read.split.take(1).first
exit if local_ref == '(delete)'

root_directory = `git rev-parse --show-toplevel`.strip
coffeelint_directories = ['app', 'spec'].map { |subdirectory| "#{root_directory}/#{subdirectory}" }
IO.popen(['coffeelint'].concat(coffeelint_directories), 'r') do |io|
  output = io.readlines
  io.close
  if $?.success?
    puts 'coffeelint: ok'
  else
    for line in output
      if l = line.match(/✗/)
        unless line.match(/Lint\!/)
          puts "\033[31m#{line}"
        end
      end
    end
    puts "\033[0m#{output[output.length - 2]}"
    exit $?.exitstatus
  end
end

branch = `git rev-parse --abbrev-ref HEAD`.strip
remote = `git config --get remote.origin.url`.strip
repository = /:(.+)\.git$/.match(remote)[1]

puts "-> https://github.com/#{repository}/compare/#{branch}"
puts ""

